### ISSUE TITLE
Remove user account dependency in tracking experiment installations

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1040]
The method we use to track experiment installations on the server (mainly for counting users) has some FxA dependencies that need changing:
- [x] [UserInstallation model](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/models.py#L112) includes a pointer to user account along with browser client ID. 
- [x] [The API](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/views.py#L47) for managing installation status requires authentication
- [x] [The add-on](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L427) uses authentication cookies as part of the request to that API.
- [x] [The `installation_count` property of the Experiment model](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/models.py#L64) counts distinct users in installation records - this should just be a straight installation count after the user column is removed.

**Comment by lmorchard** [comment]
For what it's worth, this is an interim step. Eventually, counts from Telemetry should replace this installation tracking altogether (#1039)
