### ISSUE TITLE
Test Pilot Social Solicitation

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1086]
Please see the Social Media solicitation flow here: https://invis.io/Q77S1H6ZC
### Requirements
- It should prompt active users to share Test Pilot once on a new browser session.
- it should assign special UTMs to sharing URLs to help us understand how they get shared around
- It should measure the conversion from social media shares to new installs of test pilot
### Tasks
- [x] [Create Test Pilot social media share page](https://github.com/mozilla/testpilot/issues/1096)
- [x] [Test Pilot should ask user to share after having an experiment installed for 3 days](https://github.com/mozilla/testpilot/issues/1097)
- [x] [Measure conversion of social media shares to new installs ](https://github.com/mozilla/testpilot/issues/1099)

**Comment by johngruen** [comment]
![email](https://cloud.githubusercontent.com/assets/3323249/16928285/687c448c-4cf7-11e6-9452-4ab56341af11.png)
![email 2x](https://cloud.githubusercontent.com/assets/3323249/16928288/68812a1a-4cf7-11e6-9778-7cf699987e6b.png)
![facebook](https://cloud.githubusercontent.com/assets/3323249/16928284/687c5e5e-4cf7-11e6-97a5-4972adb73c54.png)
![facebook 2x](https://cloud.githubusercontent.com/assets/3323249/16928286/687e716c-4cf7-11e6-80da-b8167d71cd35.png)
![twitter](https://cloud.githubusercontent.com/assets/3323249/16928289/68820246-4cf7-11e6-9f9a-51ce1f84641d.png)
![twitter 2x](https://cloud.githubusercontent.com/assets/3323249/16928287/687e9494-4cf7-11e6-88eb-6ecb2711e9a8.png)

OR SVG:
email: https://www.dropbox.com/s/nlksg2cjb02d7qt/Email.svg?dl=0
fb: https://www.dropbox.com/s/b32de7ytx9rnt43/Facebook.svg?dl=0
twit: https://www.dropbox.com/s/nxkpzj8rm94gln3/Twitter.svg?dl=0
