### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#130]
Tasks so far:
- [x] Implement L10N in frontend app via l20n.js
- [x] Chasing down any remaining strings lurking, e.g. in page titles & [CSS](https://github.com/mozilla/idea-town/issues/380) etc
  - See #382 & #383 
- [x] Localizing database content on the server side (#392)
- [ ] Add locales in addition to en-US (#381)
- [ ] Integrating with Pontoon (or some interface acceptable to localizers) (#414)

**Comment by lmorchard** [comment]
Relevant to these interests:
https://developer.mozilla.org/en-US/docs/Implementing_Pontoon_Mozilla
https://github.com/fabi1cazenave/webL10n
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_with_Verbatim

**Comment by pdehaan** [comment]
http://l20n.org/ also looks interesting (and built by us).

**Comment by lmorchard** [comment]
Gotcha from #342: Look for all places where we're doing plain concatenation of strings like `"Idea Town - " + pageTitle` and turn them into localizable templates. (i.e. because word order and such don't work the same way in all locales, especially for RTL languages)

**Comment by lmorchard** [comment]
Got a start on this in 8b6034b33a373d8b0e2d4d21f09a62621a755b0c

But, some things are left, such as:
- [ ] Integrating with Pontoon (or some interface acceptable to localizers)
- [ ] Localizing database content on the server side (#392)
- [x] Chasing down any remaining strings lurking, e.g. in page titles & [CSS](https://github.com/mozilla/idea-town/issues/380) etc
  - See #382 & #383

**Comment by lmorchard** [comment]
Closing this. Remaining tasks have issues.
