### ISSUE TITLE
Final configurations for new experiments

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1411]
In #1392 we pushed out partially complete YAML pages so review could happen outside of a local environment. This is opened as a follow-up and needs to be closed before launch
- [x] Confirm contributors (#1416)
- [x] Confirm tour/detail image copy (#1430)
- [x] Confirm final XPI & ID's (#1436)
- [x] Discourse needs to be set up (Bugs [1304878](https://bugzilla.mozilla.org/show_bug.cgi?id=1304878), [1304879](https://bugzilla.mozilla.org/show_bug.cgi?id=1304879), [1304880](https://bugzilla.mozilla.org/show_bug.cgi?id=1304880))
- [x] Confirm colors and image (#1414)
- [x] Add UTC launch_date to each experiment (#1409)
- [x] Add min_version: 48 to Tracking Protection (#1427)
- [x] ~~Add conflicting addons to Tracking Protection~~ #1402 is no longer a blocker
- [x] Facebook/Twitter images (#1431)
- [x] Maybe hide counts if they don't exist yet ([Ref](https://github.com/mozilla/testpilot/pull/1410/commits/67d2d9e0780d28a171df9928e703ff6488bab662#diff-5eccc665b4f05b0644484ec36a9c9c9cR117))
- [x] If #1398 add pre-feedback info for tracking protection
- [x] add surveygizmo urls (Robert confirmed over email)

**Comment by johngruen** [comment]
contribs added in #1416

**Comment by johngruen** [comment]
user counts dealt with in #1425

**Comment by johngruen** [comment]
Images finalized in: #1426

**Comment by johngruen** [comment]
@clouserw and I just realized we can skip the launch_date field and just throw the waffle flag on prod

**Comment by johngruen** [comment]
Min Version and prefeeback added to tracking protection: #1427

**Comment by ckprice** [comment]
🎉
