### ISSUE TITLE
[tracker] Security checklist

### ISSUE THREAD

**Issue by jvehent** [mozilla/testpilot#1482]
## Risk Management
- [x] The service must have performed a Rapid Risk Assessment and have a Risk Record bug (**SVC-RRA**).
## Infrastructure rules
- [x] Use [Intermediate TLS](https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility) (**INFRA-TLS**)
- [x] Set HSTS to 31536000 (1 year) (**INFRA-HSTS**)
- [x] Set HPKP to 5184000 (60 days) (**INFRA-HPKP**)
  - `Public-Key-Pins: max-age=300; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E=";`
    - Start with max-age set to 5 minutes and increase gradually
    - Pin to the EV and DV roots of Digicert
  - [x] If the service is not hosted under `services.mozilla.com`, it must be manually added to [Firefox's preloaded pins](https://dxr.mozilla.org/mozilla-central/source/security/manager/tools/PreloadedHPKPins.json#184).
- If service has an admin panels, it must:
  - [x] only be available behind Mozilla VPN (which provides MFA) (**INFRA-ADMINVPN**)
  - [x] require LDAP authentication (**INFRA-ADMINLDAP**)
  - [x] enforce a two-man rule on sensitive changes (**INFRA-2MANRULE**)
## Coding rules

The following rules apply to all web applications: api and websites.
- [x] Sign all commits (**APP-COMMITSIG**)
  - Developers should [configure git to sign all commits](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
- [x] Detailed logging in mozlog format (**APP-MOZLOG**)
  - Business logic must be logged with app specific codes (errno)
  - Access control failures must be logged at WARN level
- [x] All SQL queries must be parameterized, not concatenated (**APP-SQL**)
- [x] User data must be escaped for the right context prior to reflecting it (**APP-ESCAPE**)
- [x] Apply sensible limits to user inputs, see [input validation](https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Input_Validation) (**APP-INPUTVAL**)
- [x] Enforce Access Controls server-side (**APP-ACL**)
- [x] Set the Secure flag on [Cookies](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Cookies), and use sensible Expiration and HTTPOnly (**APP-SECCOOKIE**)
- Keep 3rd-party libraries up to date (**APP-DEPS**)
  - [x]  Use [NSP](https://nodesecurity.io/) or [GreenKeeper](https://greenkeeper.io/ Greenkeeper) for NodeJS applications
  - [x] Use pip --outdated or [requires.io](https://requires.io/) for Python applications
- [x] If handling cryptographic keys, must have a mechanism to handle monthly key rotations (**APP-KEYROT**)
  - [x] All keys must be rotated quarterly.
  - Keys used to sign sessions don't need a rotation mechanism if destroying all sessions is acceptable during.
### Additional websites requirements

The following coding rules only apply to websites, not web apis.
- [x] Never store passwords, use Firefox Accounts (**APP-IDP**)
- [x] Forbid Mixed content, always use HTTPS (**APP-MIXCONTENT**)
- [x] Must have a CSP with (**APP-CSP**)
  - [x] a report-uri pointing to the service `/__cspreport__`
  - [x] frame-options set to deny
  - [x] no use of unsafe-inline or unsafe-eval
- [x] Must have CSRF tokens and manually excluded specific forms (**APP-CSRF**)
- [x] Should consider having checksums for 3rd-party content via SRI (**APP-SRI**).
  - Trusted 3rd parties, like Google Analytics, don't need SRI. Use your best judgment to decide if a 3rd party script is trustworthy (and assume it is not).
- Consider Security headers as appropriate (**APP-HEADERS**)
  - [x] X-Content-Type-Options
  - [x] X-Frame-Options
  - [x] X-XSS-Protection
## Data rules
- When storing sensitive user data (like browsing history) on Mozilla servers:
  - [x] Anonymize it (similar to Tiles) (**DATA-ANON**)
  - [x] Encrypt it client-side (similar to Sync) (**DATA-CRYPT**)
  - [x] If user data must be stored non-anonymized and in clear text, you must talk to the security and legal teams about it.
- If the service pushes data to Firefox, like when distributing blacklists or pushing updates, cryptographic signatures must be used. (**DATA-SIGN**)
  - [x] Addons must use standard AMO signing (**APP-SIGNING**)
  - [x] Code & Conf must use Content-Signature via [Autograph](https://github.com/mozilla-services/autograph) (**DATA-SIGNING**)

**Comment by ghost** [comment]
- CSP, HSTS, x-content-type-options, x-frame-options, x-xss-protection  and HPKP are added with https://github.com/mozilla/testpilot/commit/595928ea59b171e6d9b226fb804fcb4140a6878e and are being deployed in https://bugzilla.mozilla.org/show_bug.cgi?id=1306680

**Comment by ghost** [comment]
We have an A+ on https://observatory.mozilla.org/analyze.html?host=testpilot.firefox.com now, so I'll run through and check some things off.

We don't have an admin panel or a database, so checking those off.
We don't use cookies, so checking that.  We don't accept user input, except for subscribing to the mailing list, and that has some validation on it.  We don't have forms, so no CSRF.  We had SRI for a while and removed it because it kept breaking things when they updated.  I'll call that "considering" it.

**Comment by ghost** [comment]
> If the service is not hosted under services.mozilla.com, it must be manually added to Firefox's preloaded pins.

I think this is out of my wheelhouse.  Can we check this off?

> Detailed logging in mozlog format (APP-MOZLOG)

We have stuff going into Sentry.  Does that cover this?

>  Enforce Access Controls server-side (APP-ACL)

I don't think I can answer this one.

>  Forbid Mixed content, always use HTTPS (APP-MIXCONTENT)

Is this asking for a header or setting?  We don't have non-ssl content, afaik, but I don't know that we do any "forbidding" 

ni? @jvehent for the above

**Comment by jvehent** [comment]
> > If the service is not hosted under services.mozilla.com, it must be manually added to Firefox's preloaded pins.
> 
> I think this is out of my wheelhouse. Can we check this off?

Yes. Covered in [bug 1301956](https://bugzilla.mozilla.org/show_bug.cgi?id=1301956)

> > Detailed logging in mozlog format (APP-MOZLOG)
> 
> We have stuff going into Sentry. Does that cover this?

This wouldn't apply to testpilot since it's a static site. Out of curiosity: what generates sentry logs?

> > Enforce Access Controls server-side (APP-ACL)
> 
> I don't think I can answer this one.

Doesn't apply to static sites. It applies to webapps that manage user resources with permissions.

> > Forbid Mixed content, always use HTTPS (APP-MIXCONTENT)
> 
> Is this asking for a header or setting? We don't have non-ssl content, afaik, but I don't know that we do any "forbidding" 

Forbid is probably the wrong term. This is really asking devs to make sure all content is served through HTTPS, which you do already.

I'm impressed by how well you're doing on the security checklist, thanks for putting in the effort!

The last item, signing all commits, will probably take us some time to implement correctly.

**Comment by ghost** [comment]
Sentry logs are sent from the frontend via JS to catch any JS errors.  I enabled greenkeeper.io today which was the last checkbox besides signing all commits.

Do you want to hold this open for that?  Note that commits coming from Pontoon aren't signed either (I pinged mathjazz about it).

**Comment by jvehent** [comment]
It's up to you if you want to keep it open or create another issue for signing commits.
Out of curiosity: what's holding commit signing back? Is it a matter of getting everyone to set it up, or are there issues with it?

**Comment by ghost** [comment]
No issues, we just hadn't talked about it again.  We talked about it a few weeks ago and all agreed to start signing.  New developer commits that I've seen have been signed, I think we're done here.  Thanks!
