### ISSUE TITLE
UX spec for Featured Experiments

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#2976]
@johngruen @clouserw Please find the Lucidchart link for overall flow and InVision link for the UX spec for featured experiments. Peko is working on the visual design. Let us know if any questions, thanks.

![default](https://user-images.githubusercontent.com/18019946/31766157-600c57ae-b4f9-11e7-9b69-27229f2807a5.png)

Lucidchart:
https://www.lucidchart.com/invitations/accept/89f867d6-ca3a-450a-b6cc-c1c131c7ccdd

InVision:
https://mozilla.invisionapp.com/share/QCCPNI3YZ#/258957338_a-0-0_FE_TxP_Not_Installed
(You can always click the Logo to go back to the first page.)

**Comment by chuckharmston** [comment]
A bit of concern from me in the UX meeting today: I fear that this will cannibalize installs for non-featured experiments. If the goal is to push as many conversions as possible to that experiment (as seems to be the case for Q4/Q1), that's no problem, but I'd still suggest considering this in both the visual design and UX spec. Some considerations:

- Completely collapse this section if the user already has installed the featured experiment. They're already conversions, so it'd make sense to divert their attention to other experiments.
- Be careful in the design to make sure it never takes up too much vertical space. If "or try our other experiments" is always on-screen, then this isn't a problem. But with a huge variety of screen and window sizes, that's very hard to do. (There may be some technical tricks we can do for this as well, like having that link be sticky to the bottom of the screen until the other experiments scroll into view)

**Comment by ChenMorpheus** [comment]
@chuckharmston @johngruen Sorry that I didn't have the chance to elaborate my thought in the meeting. My idea exactly is what you propose here. You can find the link below for the prototype. When we detect users' screen resolution is below a certain value, we display the strip button to remind users there are more experiments underneath. While users click the strip button, it scrolls down the page to show the rest experiments. If it's not clear, we can prepare the animation for your reference. 
Besides, I would suggest not collapsing the featured experiment if users have enabled since we need to ensure that the position still stays at where they activated, or this might cause more confusions if users come back for more information. 

![default](https://user-images.githubusercontent.com/18019946/31928140-96400df6-b8c9-11e7-9f46-9d4a2bb4ffa4.png)
(Click the strip button and it moves down to display the rest experiments)

![default](https://user-images.githubusercontent.com/18019946/31928179-b2a71ec6-b8c9-11e7-966e-da4f586efa9d.png)


https://mozilla.invisionapp.com/share/QCCPNI3YZ#/258957336_a-0-4_FE_More_experiments

**Comment by Pekochen** [comment]
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/
Here is the measurement of the main page for the featured experiment. I will provide rest of them asap. 
For the header, Please keep it temporary because we might have a bit change at this part. Sorry about that. and also for scroll hint, I would like to do a loop animation for it, something like 
![scss-arrow-animation](https://user-images.githubusercontent.com/8252151/32098535-9da993a0-bb3f-11e7-852e-62a514bb217b.gif)
Just wondering what kind of format should I provide? gif or svg or...?
Thanks for your help.

**Comment by chuckharmston** [comment]
This looks great! I see a few things with missing UX:

- [x] The modal for displaying the [experiment privacy notice](https://user-images.githubusercontent.com/23885/32179583-684999d6-bd55-11e7-966d-73f652208f0e.png)
- [x] The sticky banner for ["or try our other experiments"](https://user-images.githubusercontent.com/23885/32179657-96732368-bd55-11e7-8db1-befb74b1b075.png) (Available in https://github.com/mozilla/testpilot/issues/3001#issuecomment-341004649)
- [x] ~The experience if there are no featured experiments.~ _(Will use the existing news feed experience.)_
- [x] ~The experience if there is no video~ _(Will always have videos, for now.)_
- [x] The experience if Firefox is not being used. (Available in https://github.com/mozilla/testpilot/issues/2976#issuecomment-341020501)
- [x] How it looks [on small screens](https://user-images.githubusercontent.com/23885/32180071-9c7a8278-bd56-11e7-9e70-20c026cf6ba4.png) (Available in https://github.com/mozilla/testpilot/issues/2976#issuecomment-341020501)
- [x] The experience for the [standalone news feed page](https://user-images.githubusercontent.com/23885/32180874-bd82bee8-bd58-11e7-89df-3ae8fd224d56.png) (Available in https://github.com/mozilla/testpilot/issues/2976#issuecomment-341020501)
- [x] ~The experience for news feed item detail pages.~ _(These only link to Medium.)_

**Comment by chuckharmston** [comment]
>  Just wondering what kind of format should I provide? gif or svg or...?

We can do this with CSS animations, a static version of just one of the arrows should be fine.

**Comment by chuckharmston** [comment]
Also of note: Photonization will be happening in the next few weeks. Perhaps these should be updated to match the Photon styles?

**Comment by Pekochen** [comment]
Please see the latest update for featured experiment
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/
Thanks!

**Comment by ChenMorpheus** [comment]
>  The modal for displaying the experiment privacy notice
    The sticky banner for "or try our other experiments"
    The experience if Firefox is not being used.
    How it looks on small screens
    The experience for the standalone news feed page.

Peko will provide everything in the list above and share the details with you. 
As for other items, I would like to talk about it one by one.

> The experience if there is no video 

@johngruen I assume there will always be a video for the featured experiment, right?  If that's not the case, we can display screenshots instead and decide if we want to make them a carousel.      

>  The experience for news feed item detail pages.

Please correct me if I am wrong. I thought news feed only have two types: 1. linking to Medium; 2. No links. So I am kind of confused what news feed item detail pages are? 
    
> The experience if there are no featured experiments.

Per talked, if there are no featured experiments, we can just show what we have now.

**Comment by Pekochen** [comment]
Updated the rest of pages
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/

>Also of note: Photonization will be happening in the next few weeks. Perhaps these should be updated to match the Photon styles?

I will provide Photonized featured experiment in few days.
Thanks

**Comment by chuckharmston** [comment]
This is great, thanks @Pekochen! All we need now is the Photonized version and the modal window (#2998).

**Comment by Pekochen** [comment]
Hi @chuckharmston 
Updated a privacy page.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_Experiment_privacy/#artboard0
Thank you~

**Comment by chuckharmston** [comment]
Looks great! We're now just blocked on the Photon styles. I'll close this issue as a success, and open a new one for that: #3019.
