### ISSUE TITLE
Release for New experiments to stage

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3702]
- [x] Merge devin's l10n pr into master #3701
- [ ] JG needs to land all the new notes assets #3706 
- [x] #3683 patched
- [ ] Merge outstanding PRs #3693 (dave to review) #3681 (jg will review latter)

**Comment by devinreams** [comment]
Looks like a solid plan @johngruen 👌 I added a link directly to the l10n PR and "requested review" on the other two just to be super redundant and explicit. 😏 

Just let me know if there's anything else I can do to help support the release...
