### ISSUE TITLE
Delivery of all launch experiment details and assets

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#493]
Before we launch, we should make sure we audit the current Activity Stream info and make sure we list the correct measurements, contributors, version, and other data.

/edited by Cory
- [ ] Activity Stream assets (https://github.com/mozilla/activity-streams/issues/549)
- [ ] Universal Search assets (https://github.com/mozilla/universal-search/issues/147)
- [ ] Tab Center assets (https://github.com/bwinton/VerticalTabs/issues/65)

[Master asset tracking document](https://docs.google.com/spreadsheets/d/170wRKBJ6LV67wIwAm8flkyYaweYNejuuiZU6tENgbcg/edit#gid=0).

**Comment by ckprice** [comment]
Adding this to the 2016-04-22 milestone along with #438 which is related.

**Comment by pdehaan** [comment]
Ref: #555 **"Refresh demo_data.json with up to date info"**

After updating any Activity-Stream information in admin, we should make sure we update the demo_data.json fixture data to match.

**Comment by lmorchard** [comment]
> After updating any Activity-Stream information in admin, we should make sure we update the demo_data.json fixture data to match.

In _which_ admin? :) I'm not sure `demo_data.json` should actually match any particular environment. Data will differ between prod, stage, and dev depending on what kind of tests / research we want to run there. 

`demo_data.json` is mainly there to offer some sample data to exercise features during local dev, not to replicate what might be in production. I originally loaded the new dev server with it to have something there, but it's not necessarily the best content to have there

**Comment by lmorchard** [comment]
(oops, didn't mean to close)

**Comment by meandavejustice** [comment]
I think we should make a practice of updating demo_data.json when adding a new field or changing data shape. Just as we have to change the shape of data in our tests to get them to pass when we make changes to a model. This is probably a given, but that is my only opinion

**Comment by ckprice** [comment]
I updated this a bit to address all 3 launch candidates (as well as updated Issue opening).

I also moved it out to the `2016-05-06` milestone, as the requirements for everything should be more clear next week (e.g. after landing #575, #438).

**Comment by pdehaan** [comment]
Updated activity-stream icon in https://github.com/mozilla/activity-streams/pull/544

**Comment by pdehaan** [comment]
Not exactly related, but this seems like the best place for this useless comment.
Some of our pages are pretty beefy. We should make sure we're doing "our best"(tm) after we get our final launch assets in place:

| PAGE | REQUESTS | PAYLOAD |
| --- | :-: | --: |
| http://testpilot.dev.mozaws.net/experiments | 22 | 747 KB |
| http://testpilot.dev.mozaws.net/ (something's up) | 19 | 741 KB |
| http://testpilot.dev.mozaws.net/?{token} | 25 | 750 KB |
| http://testpilot.dev.mozaws.net/experiments/activity-stream | 25 | 2,855 KB |
| http://testpilot.dev.mozaws.net/experiments/tabcenter | 22 | 801 KB |
| http://testpilot.dev.mozaws.net/experiments/universal-search | 27 | 3,040 KB |

In some cases we're serving 1500x1000 px (800 KB) avatar photos (in case anybody else needs some high-resolution @chuckharmston wallpaper), or 1200x1200 px (600 KB) @nchapman avatar wallpaper, or else 2-3 screenshots which are 340-690 KB each.

**Comment by lmorchard** [comment]
> In some cases we're serving 1500x1000 px (800 KB) avatar photos (in case anybody else needs some high-resolution @chuckharmston wallpaper), or 1200x1200 px (600 KB) @nchapman avatar wallpaper, or else 2-3 screenshots which are 340-690 KB each.

FWIW, this is also related to #46 - we don't have a built-in thumbnail facility on the site that processes uploads, so all images should be pre-scaled & optimized for whatever sizes they need to be.

**Comment by ckprice** [comment]
[Shipped](https://docs.google.com/document/d/1g3FrhH8Neq9C9qUbfdLHRUfMsTdgTFZwgAm2aKTdQa4/edit)!
