### ISSUE TITLE
Add the ability to email Test Pilot users when new experiments become available [discussion]

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#505]
A few big things
- [x] platform to host the list and deploy emails **marketing team + basket**
- ~~create background job queue (per Les, e.g. #163)~~
- [ ] adding users to the list at add-on install (#609)
- [ ] removing users from the list at add-on disable (#609)
- [ ] designing the template (#589)
- [x] resource to deploy the emails on an ongoing basis (or auto trigger) **marketing team will provide resource for coding and deploying**
- [x] question: do we need to opt-in users with some kind of UI? **No - sign off from legal and PMM**

/cc @johngruen @javaun

**Comment by lmorchard** [comment]
A note on the engineering side: This is the kind of thing that will probably necessitate adding background job queue to our infra (i.e. #163), if only to talk to the mailing platform

**Comment by meandavejustice** [comment]
Will we want to use the basket api for this? http://basket.readthedocs.org/en/latest/newsletter_api.html

**Comment by pdehaan** [comment]
+1 to making users opt-in to emails.

**Comment by javaun** [comment]
AIUI the preferred destination is the PMM team's ExactTarget account.

**Comment by ckprice** [comment]
Noting that there is nothing here that blocks launch.

**Comment by ckprice** [comment]
Updated the bug opening with some answers and checked a couple of things off based on a meeting with PMM today.

I noted in the above comment that this does not block launch. However, we'll need some tool/thing ready to go (or near ready) at launch to be able to add users (or exclude) retroactively once the email list/bridge is all set up. We can either create a bug for this 1-off work, or try and _include #505 into the v1 scope_. @clouserw @lmorchard @meandavejustice thoughts?

Also,

> Will we want to use the basket api for this? http://basket.readthedocs.org/en/latest/newsletter_api.html

Yep!

**Comment by lmorchard** [comment]
Not entirely comfortable committing to this for public launch. A few thoughts / questions:
- What determines when a new experiment is available? Might be tricky to automate. Manually triggered emails would probably be easiest & safest so we don't accidentally notify on content that's still being edited.
- What are the exact details of the current blessed email service we have available? Is it definitely Basket and not ExactTarget [as @javaun mentioned](https://github.com/mozilla/testpilot/issues/505#issuecomment-198817071)? Is there already a push-button email blast tool available?
- If this ends up being a tool we build as part of the Test Pilot server, we'll need an offline work queue (#163) to handle the email tasks. That will probably take at least a week or two of coordinating with ops to add to our infrastructure, then time to build & test the tool.
- "marketing team will provide resource for coding and deploying" - coding what and deploying where?
- We don't currently track whether users have installed or uninstalled the main Test Pilot add-on. So, we'll need to add that. Also, we accommodate multiple browser profiles per user, so we should probably make this whether a user 1) has any installations or 2) has disabled all of them. 
  
  But, if we have that as a criteria, assembling the mailing list should be a quick DB query. That, or maybe we have to call an API for every add/remove?
- Seems like we don't need to support opt-in - but what about opt-out? As in, unsubscribe me and never email me about this again, regardless of whether I install/uninstall the add-on?

**Comment by ckprice** [comment]
I'm going to take a stab at these questions. I've worked a few projects with basket, so have a bit of experience.

> What determines when a new experiment is available? Might be tricky to automate. Manually triggered emails would probably be easiest & safest so we don't accidentally notify on content that's still being edited.

Let's not worry about automating this in v1. Manually sending the emails is fine, and will be a part of marketing's responsibilities.

> What are the exact details of the current blessed email service we have available? Is it definitely Basket and not ExactTarget as @javaun mentioned? Is there already a push-button email blast tool available?

It's Basket _and_ ExactTarget. Basket being the Python library we use to communicate with ExactTarget.

References
- https://github.com/mozilla/basket
- [(docs) Unsubscribe ](http://basket.readthedocs.org/newsletter_api.html#news-unsubscribe)
- [(example) Subscribe](https://github.com/mozilla/snippets/blob/master/campaigns/mobile/mobile-snippet-widget.html#L409)
- IRC #basket

> "marketing team will provide resource for coding and deploying" - coding what and deploying where?

John will design the email template, and marketing will _code them_ in ExactTarget. Marketing will also be responsible for _deploying (sending)_ emails when new experiments are created.

> But, if we have that as a criteria, assembling the mailing list should be a quick DB query. That, or maybe we have to call an API for every add/remove?

The mailing list will be kept on ExactTarget. Our tasks will be sending "subscribe" or "unsubscribe" calls via the Basket API on install or disable. So, yes to your question.

> Seems like we don't need to support opt-in - but what about opt-out? As in, unsubscribe me and never email me about this again, regardless of whether I install/uninstall the add-on?

Within Test Pilot, when a user "Retires" Test Pilot, we need to also unsubscribe from this mailing list (Ref: #499), so invoke the "unsubscribe" API.

The email template will contain an "Unsubscribe" button, which will remove them from the ExactTarget mailing list. New question: if they unsubscribe to the email, do we also have to disable the add-on? I think it's okay to say no here.

> If this ends up being a tool we build as part of the Test Pilot server, we'll need an offline work queue (#163) to handle the email tasks. That will probably take at least a week or two of coordinating with ops to add to our infrastructure, then time to build & test the tool.

Given the above, do you still think this is required? Everything should be triggered from user interaction.

@lmorchard let me know if/when you'd like to meet with any basket folks; I can arrange something.

/cc @bniolet1 - our marketing contact for basket integration. He'll also help with our newsletter ID.

**Comment by ghost** [comment]
Thanks les & cory.  Between cory's answers and our meeting today I think we're all on the same page.  This is an example integration I found in zamboni: https://github.com/mozilla/zamboni/commit/347bec27d688c9bfc4aeace8a9775655def5d27e  

All we're talking about here is subscribing or unsubscribing API calls.

**Comment by lmorchard** [comment]
> All we're talking about here is subscribing or unsubscribing API calls.

:+1: Yup, that's way less trouble than I was expecting with my wall-of-bullet-points comment.

**Comment by ckprice** [comment]
I'm going to go ahead and add the label, and move to the 4/22 milestone. We can confirm for sure during the next planning session.

**Comment by javaun** [comment]
Thanks for answering all those questions @ckprice . Yes, we definitely wanted to just scope this down to the subscribe/unsubscribe calls. A pure handoff to full-featured hosted service that does everything we need.

**Comment by lmorchard** [comment]
Un-assigned myself, because I seem to remember @ckprice was taking this

**Comment by ckprice** [comment]
> Un-assigned myself, because I seem to remember @ckprice was taking this

I had the action item to get the newsletter ID from the marketing team. I can go ahead and take the integration of the pings as well.

I'm going to close this bug and label as a [discussion]. Actual work is happening in #609 (integration) and #589 (email design).
